### ISSUE TITLE
[Question] How would this work with nuxt and page transitions?

### ISSUE THREAD

**Issue by bovas85** [davidkpiano/flipping#17]
I'm wondering if you had any experience or examples to add this to nuxt page transitions.

**Comment by davidkpiano** [comment]
I have not. But the basic pattern is you want to `.read()` right before the page changes, and `.flip()` right after.

If the page change loads a completely new page, you might have to use something like `localStorage`.

**Comment by bovas85** [comment]
I see, I'll give it a go then :) Thanks
