### ISSUE TITLE
Mithril FLIP

### ISSUE THREAD

**Issue by cavemansspa** [davidkpiano/flipping#5]
Hello David, thank you for all the great explanations and examples on the FLIP animations.

Thought you'd be interested in knowing that we've been iterating on a [Mithril](https://mithril.js.org/) component that helps with the FLIP approach and your material has been really helpful.

Here's a couple examples:
* [string animate](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYgAYgBkAkgAVWAK2olIAoZxGkArlDCdy0AAQKVACgCU54AB0o51+e0xO50vHLZzALwO2ABOiABuZgYwKA4S7gYhYQKxwGJizs5u5mGciS5OUFnZbtAARoikEGEG2PiYgtZgicmcROahEVEw9oUl-d6+2KydkRDRgQ5g7JT4ybGj3azTs8kZLgPZPn7LLbqTwCvwc0KxzUm6yzPHa8X9Epkb-ZGIAO7W4b13m97kIZ4fWzfTa5fLmcJXVZCYFuB5FJ4laC1eqCWLhQIAPgcMP6WABQIRm3IUHCiBCnDsOJK2CwAE9AY9NnDsutvoZjKYLBR-hTPtjCW5yKRzNYAITbYaLcYwSE3IQEn5uUEheFUgD0avMAAkyYhzK89WAwg09RLWGVxlB8MSAOYAYV8uhg5kYOHMZVp5gA1ohPa9yJx2Ch1ZrXMBvb7UlLoql0iGqWaLUZrVB7Y6BM6gmbozKjicoKwwvgDGBENZrBAymp2gH7AEsX1FeZK2oaAHWD7aQBdA452Lt-AQRisG2ITgAIUtKbT5F0ACVECY7Osm82q23OB3fV3WOEoBB8HqggHGU3lS4W1T4mkCSHzAA5CCvcxITgAcmdeC851aEdpn4gfVDUwFxyEPAQhU9MJGAgUkYDvAch3MchnWTSpiQIZsXB-fYKjATBolNP58WQ518PgJB8G8EIkJed4FQGDVzDtTAKNtajaNnejSJyRAAEcDD+TC4HMQMGiwioqjCaDYLLex8JcCpzEwGAYHIG0oEwiwZNJKjO3ggVXDNHCBFlfNCwIEsywrKsa04OsG1PRUmIAFRmZ0UOU8xNOfcJWIMRB2nDTtUhMzhYxXJshRFUUWw3Lduy+Qyfji9tOx7IJDj2FJzDQihNPwSLFTEcxEHgPAHHMVz3J4kDSoADxQ0xU0qkLgjCMYYziEqxK8V4VNKzxMDKXwYHYTDiV+HlKWSzZUs3dLdguARJjyjD8CpFknJ+c81zUbaWXaRMp1tB1ZwzW9kqYnUwiAt8KPMdgQPwJBeJguDWDvAB1PVNMwzhAMwfAqMDTzJu5Ei8IIirykqapdXexA7z+-BnQB8wv3dOHbrouwePIyjPquzUAEE-31AN2FayN2q6aUIuUq1vMAsLlM4TgQlqt7ZKJzYAHkq0XTc-PgAKYGsY7k1O9NOB6Ta3FYCh4EEEJy1rTFkM3HNzAAMh18xRXbJ6YD514oGUGjsDJTh6TfMK31sBjFUVygVbV+yNYhBoOedPXwVYb3-g4FTTfNy3rdtxBGvfR35dcRXqgAUUwaZ3Yc-lV2yDwvGAQdGBK49hf3Q845KbOHCjgMC-9wODMzwUi4PRAA-Z-5JnbPcm5bn3zAAH17uIDqbAW1CFgPVPUqBrA74vm9roLr1LuaoEk+GdMQNFZ7ta4qPrDP65+V9GfIRhJkrzcCesKADAouzd1no6hkug-D7HfVMBwchJjzgOoBPk1rAgRPkFJeB9iwhAaGYKAsQACMAAGBBRBQHFWfi-AYu0fLmAtkOFC1kwhwHgKSdOjY0E-H6p-Vg0B8ooSplmIwJgoEikQElUh9d8EIFJDNVhPwircPMGIJ2aDeGrgEaXURCJWQImurqO6D14AQAgF6NmCRlpeGei6N06M6qV08OxTsyFhQ6MEFRcGxEKS2GDFIzUP17rwFKkzWoFNAyiXGt4DAT52Iej-N8JiYY-xRg6t0WM7QwoM3MAAWixIjHxoZqa0lCtlcK3UX6RPsSrGJbhgo02AH2ZJ9dUnnxiRktyYMyKsUohxU+SI6gANsCExJH5zB52ZoeZ0mBbr7mfF+Xmbh2QMIsHicx+9+jRTFJLK00tzqyz7gPcUQwlqtDMskQRIIxxgjSEPIy8ywpLKEBZYspZywtjssQzZiJ1xpW3As-YhdWA-1HBOE6qYzrziFjNUu80Eo7k7oedunBS67UvPCJkj8dhJgmc8mWctgWwm2n0zkoESTWzxiQkoI8x4izFhLeZ4LpwvIugnEIydU4Bg1qiokwoxTtlZv3A27YcwsIPgOIUwoghwOQbxPIKoxFnOyAOMqnBMAAE0-kjECdKVgnpwma2uaZWkpd+XK0wAADVFTmVg9UIkyp2fVBVm5rSkFZQbae+qBXCsCAENlut9aKsFaqy1bKVmwkEZIrY9CEUdDpICfkVJ0UmF3P5RA4txl4qhbYQlxL2DuxrKcmFipRmG0boeRl9cPAIGbmSGiqs3z7nBLPN8oLhi4smU6NsXYTkcvPDyuNPxy65yHNXGeTdS51t0GSdo592iIw7ToEI1CxrVy9q3OuTYj5AMYLywUlK22cz9ia2VXg-aJrFXTaIjthmZ3HWfXtyxylXxvvAO+PzAqDD8E6+4pVyp6lGYja1IpmWGrvdSxJT6tbirXSmzdf9T5BERruii+7b4yuPYW89JRJEKspeOz9q4-Kc3IdgL+QQf7joAeOkBs0mzgMgdAWBCC4FIMw-cVB9cEPkEoVAfttCmGxu4RqNNSBWDyJtNYZhHK+XTt7VRu987WZLvpe+noYGX4zqo-++AgHD3AYfqe7AwmBiuqbIp4j21JGSKsKoV8KsADSvpMzeHdYwrTZIACyOBrCeBCLaT9R9jMhDM-4IIJMkiYFpIrGijALMc2s-sqyRzbKa0QIwWNVIE3zSC12GDAxwuMAylMS0SS4HCNhJeiq5LosXMELF5YCWADUuWrxUiPvowuQXzC5b2huCLOWjD-OSi2ce8gmojGiFGzsYHAVVlU0FFSTXPCxBoF2cR3xdp2Yc41pq20mK7WcxAtzpAPNeas6mcNrpsBpzJRk7IcHyaF3Ky+McKsHMbh3JAWr+WttKjWSqbxVj+EEnWHwPASB+mwBEDAgA7AADhQHA8QkgQAMGYCIdQmh+CCGEGgHbunaQED614OhHJGEfFnklEb12ChnLorEeFyPj1o6IwdrwKJMCTGPd3IOJPJ2uGx5ysEnm3wFriO0Gg7G3AM+tOEJnwBPC0iQKka0MAaSudiG+HwUcmdvlkn2+Rrw3yi5mMDIQb50iEb4ez6wGmMPq8VIjWIKOm7b1mKBzbhOdfuGgAQ5uzHrBvkRnYJnx6jfHFA2z0hR8JSTili1LMOKnkzlLU7neXy3doKPgao1nv-d3LNcq0PL9dqs7N+bzJHMQIwCkowUXafYBYEEAAZnwLb-bEf9tvmwPVIgBG4G2BV2rlP9dgA54z9ULP5g3zN7z4gQv1hq9V9r8yBvPwuzx6U6P+49eG+jU4IoLL1gSfyfrovn4y-sgj8J2B3hymDNI4GU1WfQWlsABEGiYCizT9pROdN6cmBppjh2yQw-FpZk-gqOsY-MLN1z7mhzH9P6t8zefU-A-RgGNU3BPD-DncgLnIKNqOzJ-MteIEnEAkjHhKkF1R4SRHbTFINSYJPbIRwEAAAKRAgMHaXlWIG+EINkEQDKDIJCAoMn3MEILMxCGmEIKYMIJJlCEoA4KoJADM0YP4KIKMCRkoIREIJEPgCEIkJABJgMBtGiH+XEIIJAAAGVEBsAssKgQg+DZC+YTBKwyQ9DVDHxSRGAdCTC3BCCj9FwgtLCQBnB18dswpFArQo5Jh2V4RhwYJat58IBmhmBTILR8BaQMNvhoBiQAwcdDMLADdk0N0s5Ld00mMIAWM7dMBiQUAUBIi-4Y5vg4Rvhad4jmFwDGI1QGNrc0jbdXQsiUA6IHYzlE9S4oCYDzB8DWEGc6D2ZoBudx8sIwBfAwAvR9daMh9RlXD3DNUHVwRA0ZQkBUxnFpUYFz8U9JjDxpjzAvCh9+FUs9R0sG91io4Ltk965kt1dKjUiWMcD5ihAbRAx6lVE3CNjV8x9TjwN2g3wzphiHZCMOV19Vw6kWjrAYc4cmogoSc0Q5iaAjj6odwAYABVbAK2EIFiPAZcIE5KdfVTZwARJ7MqIWKBagNAAAJgAFYUAYF89-spBgc2AwBVI+BtAIc9A0BxBy0QBfAoAvRiS6BAdpARBGBKYrNeASBEheA0AuBOBcAUANQjBsAvQbQctGA1QhTAwRSAABGBVgbUgANlVOFMoFBz4BtithEA0HZLECAA)
* [list animate](https://flems.io/#0=N4Igxg9gdgzhA2BTEAucD4EMAONEBMQAaEAMwEskZUBtUKTAW2TQDoALAF0fmPSk6IBqECAC+RekxYgAYgBkAkgAVWAK2olIAoZxGkArlDCdy0AAQKVACgCU54AB0o51+e0xO50vHLZzALwO2ABOiABuZgYwKA4S7gYhYQKxwGJizs5u5mGciS5OUFnZbtAARoikEGEG2PiYgtZgicmcROahEVEw9oUl-d6+2KydkRDRgQ5g7JT4ybGj3azTs8kZLgPZPn7LLbqTwCvwc0KxzUm6yzPHa8X9Epkb-ZGIAO7W4b13m97kIZ4fWzfTa5fLmcJXVZCYFuB5FJ4laC1eqCWLhQIAPgcMP6WABQIRm3IUHCiBCnDsOJK2CwAE9AY9NnDsutvoZjKYLBR-hTPtjCW5yKRzNYAITbYaLcYwSE3IQEn5uUEheFUgD0avMAAkyYhzK89WAwg09RLWGVxlB8MSAOYAYV8uhg5kYOHMZVp5gA1ohPa9yJx2Ch1ZrXMBvb7UlLoql0iGqWaLUZrVB7Y6BM6gmbozKjicoKwwvgDGBENZrBAymp2gH7AEsX1FeZK2oaAHWD7aQBdA452Lt-AQRisG2ITgAIUtKbT5F0ACVECY7Osm82q23OB3fV3WOEoBB8HqggHGU3lS4W1T4mkCSHzAA5CCvcxITgAcmdeC851aEdpn4gfVDUwFxyEPAQhU9MJGAgUkYDvAch3MchnWTSpiQIZsXB-fYKjATBolNP58WQ518PgJB8G8EIkJed4FQGDVzDtTAKNtajaNnejSJyRAAEcDD+TC4HMQMGiwioqjCaDYLLex8JcCpzEwGAYHIG0oEwiwZNJKjO3ggVXDNHCBFlfNCwIEsywrKsa04OsG1PRUmIAFRmZ0UOU8xNOfcJWIMRB2nDTtUhMzhYxXJshRFUUWw3Lduy+Qyfji9tOx7IJDj2FJzDQihNPwSLFTEcxEHgPAHHMVz3J4kDSoADxQ0xU0qkLgjCMYYziEqxK8V4VNKzxMDKXwYHYTDiV+HlKWSzZUs3dLdguARJjyjD8CpFknJ+c81zUbaWXaRMp1tB1ZwzW9kqYnUwiAt8KPMdgQPwJBeJguDWDvAB1PVNMwzhAMwfAqMDTzJu5Ei8IIirykqapdXexA7z+-BnQB8wv3dOHbrouwePIyjPquzUAEE-31AN2FayN2q6aUIuUq1vMAsLlM4TgQlqt7ZKJzYAHkq0XTc-PgAKYGsY7k1O9NOB6Ta3FYCh4EEEJy1rTFkM3HNzAAMh18xRXbJ6YD514oGUGjsDJTh6TfMK31sBjFUVygVbV+yNYhBoOedPXwVYb3-g4FTTfNy3rdtxBGvfR35dcRXqgAUUwaZ3Yc-lV2yDwvGAQdGBK49hf3Q845KbOHCjgMC-9wODMzwUi4PRAA-Z-5JnbPcm5bn3zAAH17uIDqbAW1CFgPVPUqBrA74vm9roLr1LuaoEk+GdMQNFZ7ta4qPrDP65+V9GfIRhJkrzcCesKADAouzd1no6hkug-D7HfVMBwchJjzgOoBPk1rAgRPkFJeB9iwhAaGYKAsQACMAAGBBRBQHFWfi-AYu0fLmAtkOFC1kwhwHgKSdOjY0E-H6p-Vg0B8ooSplmIwJgoEikQElUh9d8EIFJDNVhPwircPMGIJ2aDeGrgEaXURCJWQImurqO6D14AQAgF6NmCRlpeGei6N06M6qV08OxTsyFhQ6MEFRcGxEKS2GDFIzUP17rwFKkzWoFNAyiXGt4DAT52Iej-N8JiYY-xRg6t0WM7QwoM3MAAWixIjHxoZqa0lCtlcK3UX6RPsSrGJbhgo02AH2ZJ9dUnnxiRktyYMyKsUohxU+SI6gANsCExJH5zB52ZoeZ0mBbr7mfF+Xmbh2QMIsHicx+9+jRTFJLK00tzqyz7gPcUQwlqtDMskQRIIxxgjSEPIy8ywpLKEBZYspZywtjssQzZiJ1xpW3As-YhdWA-1HBOE6qYzrziFjNUu80Eo7k7oedunBS67UvPCJkj8dhJgmc8mWctgWwm2n0zkoESTWzxiQkoI8x4izFhLeZ4LpwvIugnEIydU4Bg1qiokwoxTtlZv3A27YcwsIPgOIUwoghwOQbxPIKoxFnOyAOMqnBMAAE0-kjECdKVgnpwma2uaZWkpd+XK0wAADVFTmVg9UIkyp2fVBVm5rSkFZQbae+qBXCsCAENlut9aKsFaqy1bKVmwkEZIrY9CEUdDpICfkVJ0UmF3P5RA4txl4qhbYQlxL2DuxrKcmFipRmG0boeRl9cPAIGbmSGiqs3z7nBLPN8oLhi4smU6NsXYTkcvPDyuNPxy65yHNXGeTdS51t0GSdo592iIw7ToEI1CxrVy9q3OuTYj5AMYLywUlK22cz9ia2VXg-aJrFXTaIjthmZ3HWfXtyxylXxvvAO+PzAqDD8E6+4pVyp6lGYja1IpmWGrvdSxJT6tbirXSmzdf9T5BERruii+7b4yuPYW89JRJEKspeOz9q4-Kc3IdgL+QQf7joAeOkBs0mzgMgdAWBCC4FIMw-cVB9cEPkEoVAfttCmGxu4RqNNSBWDyJtNYZhHK+XTt7VRu987WZLvpe+noYGX4zqo-++AgHD3AYfqe7AwmBiuqbIp4j21JGSKsKoV8KsADSvpMzeHdYwrTZIACyOBrCeBCLaT9R9jMhDM-4IIJMkiYFpIrGijALMc2s-sqyRzbKa0QIwWNVIE3zSC12GDAxwuMAylMS0SS4HCNhJeiq5LosXMELF5YCWADUuWrxUiPvowuQXzC5b2huCLOWjD-OSi2ce8gmojGiFGzsYHAVVlU0FFSTXPCxBoF2cR3xdp2Yc41pq20mK7WcxAtzpAPNeas6mcNrpsBpzJRk7IcHyaF3Ky+McKsHMbh3JAWr+WttKjWSqbxVj+EEnWHwPASB+mwBEDAgA7AADhQHA8QkgQAMGYCIdQmh+CCGEGgHbunaQED614OhHJGEfFnklEb12ChnLorEeFyPj1o6IwdrwKJMCTGPd3IOJPJ2uF2p5t8BaN0v08LSJAqRrQwBpK52Ib4fBRzfMl4q7QaDsbcHTm+DPgDM9Zw4Xn9VucAFY4EAFIGdvlkn2+Rrw3zc5mMDIQ-P4ieY04RvhmSReKhnbEFHTdt6zFA5twn3CGPN2Y9YN8M67AM+Pbb44oHzeZ12sLx3puHAcxAjAKSjBudh9gFgQQABmfA1gCPhPgcrogcDbAM4gNgFOAZ4nmCSybkPq5gAx4j9UKP5gc3QEQNn3PYB8+wOZCXgYXZ-cgo7wMRGVvvc73t3vdLrf3DQAIS7iALG3yI09+0PvdvZPydN0fCUk4pYtSzDip5M5S1z+OF8rvioj4GqNSvrfK7OoyilbJ1fEKbQLslQfnaGPzBB+H4qMvEDYCR+j5-mAcfECJ7J5EBvj7bH77ZvjYD1QZ5Z7tA55542yxBF6P6l7l7f7V7l7-6AEEbYEwHNgN5N7mAwIt5v5uDt7B71zEGt7ny95bz94L4O4kFZyj7ppMYT5u7nwz55o250ESiL58KB7IFNgf7h5oE16aT17wEF5EHF6MElDCFf6V4-7h6YFJ4ABM8uSuRAaemhmeEhjeCBhelBJBZBJBRhrCZhpCs2rm7mQ41gJOq25mo0nAigWWfBmwjsMhaCYu8AEuUuG8MuSAcu1eiuKu7QaupIGuT42u1euu4EBu7QVh82i29hrAa21gThLhQWsc5B5gJhTYJG4G3wymBmSOAyTUmRnmJOFRUWNOz+dOvgEubUVRWW8QzRWRRRjwkiO2mKQakwmCAAymONYK-m4DAu0Koe0PHs4JFo8MODBLVnYRAM0MwKZBaPgLSBht8NAMSAGDjoZhYNbsmozm4M7qwZPq6MSCgCgNsX-DHEUYRt8NjiKPjgwYxGqKca7lPpgJcSgHRA7GcgIYTnTtaOEAziMaQnTmUAYOzNABLo-tAGAL4GAF6FbrRm-kfJpPVM4StEEGZoGKkZgPVAHNgDSPSNfEBokTYZ5j0UJvtjAoIa4KMpidiQjpahEooJRjsTbDUa3jSX0W8OYIMRSDQDAjMTkS-FWuKUpgyeCIGjKEDEnsyRyfZI-gLpnPEG+CTMDA7J4S-JCdCQDFAHCVKf0AiUiSiSKGicPkfK6PVMqZMHiewASUSTgKSZJgkS5kkbYTSdkSQTSXcmVGOGWLacqW4dKSafwmEQuIjDqf7vqTCUaRhiXmaeQMiaia8cPmNAYIakgAAGpylcIh5qkiJhH9HsDZm87-E5F5GKh1KlyeYw5w5NRBQk5ohykCK6mkFnK44WBZk5mID5mixBooqlxjqemTCUkLbelyl8FSQihHxIbKSelMZCA2jOLSowIADcyE5gWIcC255A4S4SPJmwR8agDpDQTpPgCiqsjphYz0th9gAAVPenSY7JuRyjQO0nNmWu0N+a5jQGoF2HFl+Z6YBeWkuT+eQMBR+YTsWW4HyUEAMUMf+bSGBrwusAIk9oGa9tQGgPAqoSgKof9lIMDmwGAKpHwNoBDnoGgOIOWiAL4FAF6HhXQIDtICIIwJTFZrwCQIkLwGgFwJwLgCgBqEYNgF6HfpAIwGqFxYGDxQAAIwKsDKUABssl3FlAoOfANsVsIgGg9FYgQAA)

**Comment by cavemansspa** [comment]
@davidkpiano -- do you have any advice / recommendation for normalizing `getBoundingClientRect()` return objects? for edge and ie, the returned object is `ClientRect` with no `x` / `y` vs the standard `DOMRect`.

**Comment by davidkpiano** [comment]
`x` would be `left` and `y` would be `top`, is that what you're asking?

**Comment by cavemansspa** [comment]
yes, i'm calculating the deltas and passing back to the user.

https://github.com/cavemansspa/mithril-list-animation/blob/master/src/FLIP.js#L113

i have the results of `getBoundingClient()` and pre-calc the deltas which are passed back to the user's callbacks. in edge / ie, `x `/ `y` don't exist, so want to isolate the browser specifics from the user so they get the deltas already prepared for them as part of the FLIP component.

**Comment by cavemansspa** [comment]
Moved to https://github.com/cavemansspa/mithril-flip

Thanks again @davidkpiano for the helpful write-ups.
