### ISSUE TITLE
How do i import this into a typescript code-base?

### ISSUE THREAD

**Issue by codepunkt** [davidkpiano/flipping#6]
I'm working on a react app written in typescript, based on `create-react-app` with `react-scripts-ts`.
Trying to import this library, i failed miserably.

- `import Flipping from 'flipping'`
→ module has no default export
- `import * as Flipping from 'flipping'`
→ module resolves to a non-module entity and cannot be imported using this construct
- `import Flippin = require('flipping')`
→ import assignment cannot be used when targeting ECMAScript modules

I would really like to test this library, but i'm rather new to typescript and really struggling with this. What can i do - preferrably without changing my typescript settings?

My `tsconfig.json` settings are
```javascript
{
  "module": "esnext",
  "target": "es5"
}
```

**Comment by davidkpiano** [comment]
Try setting `allowSyntheticDefaultImports` to `true`.

**Comment by codepunkt** [comment]
@davidkpiano I know this is rather out of scope for this project. Couldn't find any information on this whatsoever yesterday, so this helps a lot. Thanks!
