### ISSUE TITLE
TypeError: mitt is not a constructor

### ISSUE THREAD

**Issue by tsiq-swyx** [davidkpiano/flipping#7]
just trying to use Flipping with React as outlined in this article: https://css-tricks.com/animating-layouts-with-the-flip-technique/

![image](https://user-images.githubusercontent.com/35976578/39972666-55cf9a54-56e2-11e8-9e2e-7eb82e28b99e.png)

the versions of mitt and flipping all seem to check out, im not sure what i am missing here to be honest. just reporting this as it seems something broke along the way

**Comment by davidkpiano** [comment]
Want to make a PR? 

Related issue: https://github.com/developit/mitt/pull/67

**Comment by tsiq-swyx** [comment]
im still a little fuzzy about how typescript compiles these exports (i just edited the compiled javascript by hand) so bear with me but dont we want that mitt#67 issue merged first? 

if i were to edit Flipping.ts it would go from 

```ts
import * as mitt from 'mitt';
```
to

```ts
import {default as mitt} from 'mitt';
```

and then someday down the line i'd have to revert it after that mitt PR is merged?

**Comment by davidkpiano** [comment]
I doubt that PR will ever be merged, so the way it works with your fix should be good.
